
DROP TABLE [TB_MENU_MANAGER];

CREATE TABLE "TB_MENU_MANAGER"(
[MM_MENU_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[MM_MENU_DISPLAY_INDEX] integer NOT NULL
,[MM_MENU_DESC] text NOT NULL
,[MM_MENU_LANG_SRNO] text
,[MM_PARENT_SRNO] integer NOT NULL
,[MM_IS_LEAF] integer NOT NULL
,[MM_MENU_CATEGORY] integer NOT NULL
,[MM_URL] text
,[MM_TARGET] text
,[MM_CREATE_USER_SRNO] integer NOT NULL
,[MM_CREATE_DATE_TIME] datetime NOT NULL
,[MM_UPDATE_USER_SRNO] integer
,[MM_UPDATE_DATE_TIME] datetime
  
);
