DROP TABLE [TB_SYSTEM_MESSAGE];

CREATE TABLE [TB_SYSTEM_MESSAGE](
[SM_SYSTEM_MESSAGE_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[SM_MESSAGE_TIME] datetime NOT NULL
,[SM_MESSAGE_TYPE] integer NOT NULL
,[SM_SYSTEM_MESSAGE] text NOT NULL
,[SM_MESSAGE_LEVEL] integer NOT NULL
,[SM_CREATE_USER_SRNO] integer NOT NULL
  
);