'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Manager 类。
'''</summary>
'''<remarks>
'''自动生成的类。
'''</remarks>
Partial Public Class Manager

  '''<summary>
  '''masterForm 控件。
  '''</summary>
  '''<remarks>
  '''自动生成的字段。
  '''要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
  '''</remarks>
  Protected WithEvents masterForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''modContentPlaceHolder 控件。
  '''</summary>
  '''<remarks>
  '''自动生成的字段。
  '''要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
  '''</remarks>
  Protected WithEvents modContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
