// Code Master Description

var GLOBAL_CODE_MASTER_DESC = {
  GCD_EXCEPTION_STATUS: "EXCEPTION_STATUS",
  GCD_LOG_CATEGORY:     "LOG_CATEGORY"
};

var GLOBAL_CODE_MASTER_DISPLAY_FIELD = "jsCodeLabelLangDesc";
var GLOBAL_CODE_MASTER_VALUE_FIELD = "jsCodeValueLangDesc";
var GLOBAL_CODE_MASTER_QUERY = "jsCustomQuery";
var GLOBAL_CODE_MASTER_ARRAY_READER = [
  {name: GLOBAL_CODE_MASTER_DISPLAY_FIELD, mapping: GLOBAL_CODE_MASTER_DISPLAY_FIELD},
  {name: GLOBAL_CODE_MASTER_VALUE_FIELD, mapping: GLOBAL_CODE_MASTER_VALUE_FIELD},
  {name: GLOBAL_CODE_MASTER_QUERY, mapping: GLOBAL_CODE_MASTER_QUERY}
];
