
DROP TABLE "TB_CODE_MASTER";

CREATE TABLE "TB_CODE_MASTER"(
[CMS_CODE_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[CMS_CODE_DESC] text NOT NULL
,[CMS_CODE_NAME] text NOT NULL
,[CMS_CODE_LABEL] text NOT NULL
,[CMS_CODE_LABEL_LANG_SRNO] text
,[CMS_CODE_CATEGORY] integer NOT NULL
,[CMS_CODE_VALUE] text NOT NULL
,[CMS_CODE_VALUE_LANG_SRNO] text
,[CMS_CUSTOM_QUERY] text
,[CMS_CREATE_USER_SRNO] integer NOT NULL
,[CMS_CREATE_DATE_TIME] datetime NOT NULL
,[CMS_UPDATE_USER_SRNO] integer
,[CMS_UPDATE_DATE_TIME] datetime
  
);
