
DROP TABLE [TB_FILE_MANAGER];

CREATE TABLE [TB_FILE_MANAGER](
[FM_FILE_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[FM_DATE_TIME] datetime NOT NULL
,[FM_FILE_NAME] text NOT NULL
,[FM_FILE_PATH] text NOT NULL
,[FM_FILE_CATEGORY] text NOT NULL
,[FM_STATUS] integer NOT NULL
,[FM_UPDATE_USER_SRNO] integer
,[FM_UPDATE_TIME] datetime
  
);
