
DROP TABLE [TB_LOG_MANAGER];

CREATE TABLE "TB_LOG_MANAGER"(
[LM_LOG_FILE_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[LM_DATE_TIME] datetime NOT NULL
,[LM_CATEGORY] integer NOT NULL
,[LM_LEVEL] integer NOT NULL
,[LM_LOG_FILE_NAME] text
  
);
