
DROP TABLE [TB_PARAMETER_MASTER];

CREATE TABLE "TB_PARAMETER_MASTER"(
[PM_PARAMETER_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[PM_PARAMETER_DESC] text UNIQUE NOT NULL
,[PM_PARAMETER_NAME] text
,[PM_PARAMETER_NAME_LANG_SRNO] text
,[PM_PARAMETER_CATEGORY] integer NOT NULL
,[PM_VALUE_TYPE] integer NOT NULL
,[PM_VALUE] text NOT NULL
,[PM_VALUE_LANG_SRNO] text
,[PM_OPTIONS] text
,[PM_CREATE_USER_SRNO] integer NOT NULL
,[PM_CREATE_DATE_TIME] datetime NOT NULL
,[PM_UPDATE_USER_SRNO] integer
,[PM_UPDATE_DATE_TIME] datetime
  
);
