
DROP TABLE "TB_USER_LOGIN_DTLS";

CREATE TABLE "TB_USER_LOGIN_DTLS"(
[ULD_USER_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[ULD_USER_PSW] text NOT NULL
,[ULD_LOGIN_TIME] datetime
,[ULD_LAST_LOGIN_TIME] datetime
  
);
