
DROP TABLE [TB_USER_DTLS];

CREATE TABLE "TB_USER_DTLS"(
[UD_USER_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[UD_USER_NAME] text NOT NULL
,[UD_USER_SEX] integer NOT NULL
,[UD_USER_BIRTHDAY] datetime
,[UD_USER_BLOOD_TYPE] integer
,[UD_USER_TEL] text
,[UD_USER_MOBLIE] text
,[UD_USER_EMAIL] text
,[UD_USER_ADDRS] text
,[UD_USER_COUNTRY] text
,[UD_USER_DESC] text
,[UD_USER_CATEGORY] integer
,[UD_USER_STATUS] integer NOT NULL
,[UD_CREATE_USER_SRNO] integer NOT NULL
,[UD_CREATE_DATE_TIME] datetime NOT NULL
,[UD_UPDAET_USER_SRNO] integer
,[UD_UPDATE_DATE_TIME] datetime
  
);
