
DROP TABLE [TB_USER_CUSTOM_DTLS];

CREATE TABLE "TB_USER_CUSTOM_DTLS"(
[UCD_ITEM_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[UCD_ITEM_CODE] text UNIQUE NOT NULL
,[UCD_ITEM_NAME] text NOT NULL
,[UCD_ITEM_CATEGORY] integer NOT NULL
,[UCD_ITEM_STATUS] integer NOT NULL
,[UCD_CREATE_USER_SRNO] integer NOT NULL
,[UCD_CREATE_DATE_TIME] datetime NOT NULL
,[UCD_UPDATE_USER_SRNO] integer
,[UCD_UPDATE_DATE_TIME] datetime
  
);
