PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "TB_USER_CUSTOM_DTLS"(
[UCD_ITEM_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[UCD_ITEM_CODE] text UNIQUE NOT NULL
,[UCD_ITEM_NAME] text NOT NULL
,[UCD_ITEM_CATEGORY] integer NOT NULL
,[UCD_ITEM_STATUS] integer NOT NULL
,[UCD_CREATE_USER_SRNO] integer NOT NULL
,[UCD_CREATE_DATE_TIME] datetime NOT NULL
,[UCD_UPDATE_USER_SRNO] integer
,[UCD_UPDATE_DATE_TIME] datetime
  
);
CREATE TABLE [TB_USER_DTLS_MAP](
[UDM_USER_SRNO] integer NOT NULL
,[UDM_UCD_ITEM_SRNO] integer NOT NULL
,[UDM_CONTEXT] text
  
);
CREATE TABLE "TB_USER_LOGIN_DTLS"(
[ULD_USER_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[ULD_USER_PSW] text NOT NULL
,[ULD_LOGIN_TIME] datetime
,[ULD_LAST_LOGIN_TIME] datetime
  
);
CREATE TABLE [TB_FILE_MANAGER](
[FM_FILE_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[FM_DATE_TIME] datetime NOT NULL
,[FM_FILE_NAME] text NOT NULL
,[FM_FILE_PATH] text NOT NULL
,[FM_FILE_CATEGORY] text NOT NULL
,[FM_STATUS] integer NOT NULL
,[FM_UPDATE_USER_SRNO] integer
,[FM_UPDATE_TIME] datetime
  
);
CREATE TABLE "TB_USER_DTLS"(
[UD_USER_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[UD_USER_NAME] text NOT NULL
,[UD_USER_SEX] integer NOT NULL
,[UD_USER_BIRTHDAY] datetime
,[UD_USER_BLOOD_TYPE] integer
,[UD_USER_TEL] text
,[UD_USER_MOBLIE] text
,[UD_USER_EMAIL] text
,[UD_USER_ADDRS] text
,[UD_USER_COUNTRY] text
,[UD_USER_DESC] text
,[UD_USER_CATEGORY] integer
,[UD_USER_STATUS] integer NOT NULL
,[UD_CREATE_USER_SRNO] integer NOT NULL
,[UD_CREATE_DATE_TIME] datetime NOT NULL
,[UD_UPDAET_USER_SRNO] integer
,[UD_UPDATE_DATE_TIME] datetime
  
);
CREATE TABLE [TB_LANG_DICTIONARY](
[LD_ITEM_SRNO] integer NOT NULL
,[LD_ITEM_LANG] integer NOT NULL
,[LD_DESC] text NOT NULL
  
);
CREATE TABLE "TB_MESSAGE_DICTIONARY"(
[MD_MESSAGE_SRNO] integer NOT NULL
,[MD_MESSAGE_LANG] integer NOT NULL
,[MD_MESSAGE_DESC] text NOT NULL
  
);
CREATE TABLE [TB_CODE_MASTER](
[CMS_CODE_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[CMS_CODE_DESC] text NOT NULL
,[CMS_CODE_NAME] text NOT NULL
,[CMS_CODE_LABEL] text NOT NULL
,[CMS_CODE_LABEL_LANG_SRNO] integer
,[CMS_CODE_CATEGORY] integer NOT NULL
,[CMS_CODE_VALUE] text NOT NULL
,[CMS_CODE_VALUE_LANG_SRNO] integer
,[CMS_CUSTOM_QUERY] text
,[CMS_CREATE_USER_SRNO] integer NOT NULL
,[CMS_CREATE_DATE_TIME] datetime NOT NULL
,[CMS_UPDATE_USER_SRNO] integer
,[CMS_UPDATE_DATE_TIME] datetime
  
);
CREATE TABLE "TB_EXCEPTION_MANAGER"(
[EM_EXCEPTION_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[EM_DATE_TIME] datetime NOT NULL
,[EM_TITLE] text NOT NULL
,[EM_CONTEXT] text NOT NULL
,[EM_STATUS] integer NOT NULL
,[EM_UPDATE_USER_SRNO] integer
,[EM_UPDATE_TIME] datetime
  
);
CREATE TABLE "TB_COLUMN_DATA_READER"(
[CDR_COLUMN_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[CDR_VIEW_SRNO] integer NOT NULL
,[CDR_DATA_INDEX_NAME] text NOT NULL
,[CDR_MAPPING] text
,[CDR_CREATE_USER_SRNO] integer NOT NULL
,[CDR_CREATE_DATE_TIME] datetime NOT NULL
,[CDR_UPDATE_USER_SRNO] integer
,[CDR_UPDATE_DATE_TIME] datetime
  
);
CREATE TABLE [TB_SYSTEM_MESSAGE](
[SM_SYSTEM_MESSAGE_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[SM_MESSAGE_TIME] datetime NOT NULL
,[SM_MESSAGE_TYPE] integer NOT NULL
,[SM_SYSTEM_MESSAGE] text NOT NULL
,[SM_MESSAGE_LEVEL] integer NOT NULL
,[SM_CREATE_USER_SRNO] integer NOT NULL
  
);
CREATE TABLE "TB_COLUMN_MODEL"(
[CM_COLUMN_SRNO] integer UNIQUE NOT NULL
,[CM_VIEW_SRNO] integer NOT NULL
,[CM_COLUMN_NAME] text NOT NULL
,[CM_COLUMN_LANG_SRNO] integer
,[CM_COLUMN_INDEX] integer NOT NULL
,[CM_COLUMN_CATEGORY] integer NOT NULL
,[CM_COLUMN_DATA_INDEX] text NOT NULL
,[CM_COLUMN_TYPE] text
,[CM_COLUMN_WIDTH] float
,[CM_COLUMN_ALIGN] integer
,[CM_COLUMN_TOOLTIP] text
,[CM_COLUMN_CSS] text
,[CM_COLUMN_TPL] text
,[CM_COLUMN_SORTABLE] integer
,[CM_COLUMN_RESIZABLE] integer
,[CM_COLUMN_EDITABLE] integer
,[CM_COLUMN_EDITOR] text
,[CM_COLUMN_RENDERER] text
,[CM_COLUMN_SCOPE] text
,[CM_CREATE_USER_SRNO] integer NOT NULL
,[CM_CREATE_DATE_TIME] datetime NOT NULL
,[CM_UPDATE_USER_SRNO] integer
,[CM_UPDATE_DATE_TIME] datetime
  
);
CREATE TABLE "TB_LOG_MANAGER"(
[LM_LOG_FILE_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[LM_DATE_TIME] datetime NOT NULL
,[LM_CATEGORY] integer NOT NULL
,[LM_LEVEL] integer NOT NULL
,[LM_LOG_FILE_NAME] text
  
);
CREATE TABLE "TB_MENU_MANAGER"(
[MM_MENU_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[MM_MENU_DISPLAY_INDEX] integer NOT NULL
,[MM_MENU_DESC] text NOT NULL
,[MM_MENU_LANG_SRNO] integer
,[MM_PARENT_SRNO] integer NOT NULL
,[MM_IS_LEAF] integer NOT NULL
,[MM_MENU_CATEGORY] integer NOT NULL
,[MM_URL] text
,[MM_TARGET] text
,[MM_CREATE_USER_SRNO] integer NOT NULL
,[MM_CREATE_DATE_TIME] datetime NOT NULL
,[MM_UPDATE_USER_SRNO] integer
,[MM_UPDATE_DATE_TIME] datetime
  
);
CREATE TABLE "TB_PARAMETER_MASTER"(
[PM_PARAMETER_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[PM_PARAMETER_DESC] text UNIQUE NOT NULL
,[PM_PARAMETER_NAME] text
,[PM_PARAMETER_NAME_LANG_SRNO] integer
,[PM_PARAMETER_CATEGORY] integer NOT NULL
,[PM_VALUE_TYPE] integer NOT NULL
,[PM_VALUE] text NOT NULL
,[PM_VALUE_LANG_SRNO] integer
,[PM_OPTIONS] text
,[PM_CREATE_USER_SRNO] integer NOT NULL
,[PM_CREATE_DATE_TIME] datetime NOT NULL
,[PM_UPDATE_USER_SRNO] integer
,[PM_UPDATE_DATE_TIME] datetime
  
);
CREATE TABLE [TB_COLUMN_FILTER_MANAGER](
[CFM_FILTER_SRNO] integer PRIMARY KEY UNIQUE NOT NULL
,[CFM_FILTER_TYPE] text NOT NULL
,[CFM_FILTER_DATA_INDEX] text NOT NULL
,[CFM_FILTER_DISABLED] integer
,[CFM_FILTER_CODE_DESC] text
  
);
COMMIT;
